### ISSUE TITLE
Proposal for restructring onboarding process for new developers.

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/VISION-ROADMAP-FEATURES#18]
# Summary:

Right now our documentation is not well laid out to handle new developers. This is my proposal how to handle contributions and make the onboarding process more convenient.

# Table of content
1. Problems of the current state
2. Proposal for new onboarding 
3. To-Dos

### 1. Problems of the current state:
1. No clear direction on how to contribute in the different possible ways like feature dev, infra dev and bug or feature requests. 
2. It is not clear yet how to set up hypothes.is to start tinkering around on the code and then be able to contribute
3. No Feedback loop to constantly improve documentation.
4. No way to get to know other collaborateurs

### 2. Proposal for new onboarding

Here is the current version flow chart, which can be accessed by everyone.
Improvement suggestions welcome.
I have not put the thinking into the WorldBrain Repo yet, since we are not going to develop our own features in the next weeks I assume.
 (Click to enlarge) ![](http://www.gliffy.com/go/publish/image/10274819/L.png)

#### Legend of Flow chart

**Circles** are markdown files in the repo
**Triangles** are GitHub issues 
**Round Squares** are instructions 
**Lines** are actions

##### **Goal:** Getting information about the project
Steps:
1. Start Here Repo
2. Read readme.md (Abstracts)
3. Jump in desired sub repo
 - Contributing.md(same repo)
 - Roadmap (former vision) readme
 - Infrastructure readme
 - Team readme
 - How to setup.md (same repo)
 

##### **Goal:** Starting to contribute
Steps:
1. Start-Here Repo
2. Contributing (Always with: Most important task + beginner task)
 - My first time here
 - Feature Development
 - Infrastructure Development (Which Technologies in abstract)
 - Add a Feature Request
 - Add a bug you found
 - Fix a bug
 - How do I set everything up to tinker around?
3. How to setup.md
4. Choose Beginner Task to work on
5. My first Pull Request

### 3. To-Dos

- [x] Template Profile 
- [ ] For every Repo Readme.md 
 - [x] Start here 
 - [x] Hypothes.is clear fork
 - [x] Roadmap (former Vision)
 - [ ] Infrastructure
 - [x] Team
- [x] Contribution.md
- [x] How-to-Setup.md
- [x] Survey about onboarding
- [x] Template On-boarding Feedback
- [x] Template Bug (Prio 2)
- [x] Template Feature Request (Prio 2)
- [ ] Template Infra Feature Request (Prio 2)
- [x] CLA
- [x] Beginner Task
- [x] Template Team

**Comment by lwm** [comment]
Woooahhhh. That is some crazy chart! 

I think you are approaching micro-management here. I would argue that creating sub-repos and/or duplicating documentation will only cause more confusion.

I think all of the problems are solved: 

> No way to get to know other collaborateurs.

It isn't getting any better than: https://gitter.im/WorldBrain/Webmarks. Is it?

> No Feedback loop to constantly improve documentation.

Github issues are the feedback loop. Anyone can create one. I've already been able to improve it in some way with [#3102][1].

> It is not clear yet how to set up hypothes.is to start tinkering around on the code and then be able to contribute

The [installation documentation][2] is the entry point. It's pretty wordy but it covers many use cases. The entire [contribution guide][4] is actually pretty comprehensive.

> No clear direction on how to contribute in the different possible ways like feature dev, infra dev and bug or feature requests. 

I thought this was already covered with the [webmarks documentation][3].

I hope you've got used to my blunt opinions ;)

[1]: https://github.com/hypothesis/h/pull/3102
[2]: https://h.readthedocs.org/en/latest/hacking/install.html
[3]: https://github.com/WorldBrain/Webmarks#introduction
[4]: https://h.readthedocs.org/en/latest/hacking/index.html
[5]: http://c2.com/cgi/wiki?PrematureOptimization

**Comment by oliversauter** [comment]
It looks more complicated than it would look at the end.  :)

I would argue that our onboarding process is not ideal through the chats that I had with people who went through the repo. People have only a limited attention span, regardless of their intellect and IQ.

There is no doubt that our documentation has to be improved, since it is basically V0.2. 
There is always room to improve.
In making the onboarding process as smooth as possible from a narrative point of view, we make it easy for new people to understand what they are looking for. 

Regarding new developers. Many of the people I spoke to were amazed of the project and wanted to contribute, but have only limited time to do so (due to jobs etc). They would love to contribute in an effortless way in just doing a feature once in a while. They dont want to hassle through an unclear documentation.

Sure, we also can argue, that these are not the people we are looking for in terms of commitment, but small scale contributions will be an important part in the future.

And if we get even those convinced to join, then our documentation is so time saving and clear, that we have nothing to worry about.

**Comment by oliversauter** [comment]
> No way to get to know other collaborateurs.
It isn't getting any better than: https://gitter.im/WorldBrain/Webmarks. Is it?

I mean like you guys :)
I think that people who work on the project should be fairly attributed. 
Right now there is no space for that. 

Another aspect is the inspiration from the Mozilla group, where one person mentioned how well it worked to have a repo for the team, where every member has an issue as his/her profile. 

It was great because everyone could see where people want to improve and what they are already good at. Through this transparency, teams could more naturally form based on what challenges were ahead.

**Comment by oliversauter** [comment]
PLUS: Regarding the chart: I may not have yet found the most efficient way to display it simply. ;) But as said, it is easier to use than it look like in this chart.

**Comment by oliversauter** [comment]
So this is except for the infrastructure, which soon needs some overhaul again anyway, all done! :)

You can check it out here: https://github.com/WorldBrain/START-HERE/blob/master/README.md
